site_name: !ENV [SITE_NAME, "my github pages site"]
site_url: !ENV [SITE_URL, ""]
site_dir: !ENV [SITE_DIR, "site"]
docs_dir: !ENV [DOCS_DIR, "content"]
repo_url: !ENV [REPO_URL, ""]
theme: material

plugins:
  - search
  - macros:
        modules: [mkdocs-macros-file-include]
nav:
  - "Home": "index.md"
