name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}

  container:
    runs-on: ubuntu-latest
    container: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    steps:
      - name: Run in container - list user local bin
        run: |
          ls -lah /usr/local/bin
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
